name: ai_diary_matching
description: AI 기반 성격 매칭 일기장 & 소개 플랫폼
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_serializable: ^6.7.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.2.1

  # UI & 애니메이션
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # 로컬 저장소
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 유틸리티
  intl: ^0.19.0
  uuid: ^4.2.1
  logger: ^2.0.2+1

  # 이미지 & 파일
  image_picker: ^1.0.5
  path_provider: ^2.1.1

  # 위치 & 권한
  geolocator: ^10.1.0
  permission_handler: ^11.1.0

  # 네트워킹 & 보안
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # 코드 생성
  build_runner: ^2.4.7
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/